d-apache-letsencrypt-proxy-reverse:
  ports:
  - 2222:22/tcp
  - 80:80/tcp
  - 443:443/tcp
  environment:
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_SSH_ACCESS: 'true'
    DWL_USER_ID: '1000'
    DWL_SSLKEY_C: EU
    DWL_SSLKEY_ST: France
    DWL_SSLKEY_L: Vannes
    DWL_SSLKEY_O: davask web limited - docker container
    DWL_SSLKEY_CN: davaskweblimited.com
    DWL_CERTBOT_EMAIL: docker@davaskweblimited.com
  labels:
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: proxy-reverse-letsencrypt.davaskweblimited.com
  image: davask/d-apache-letsencrypt-proxy-reverse:2.4-u12.04
  volumes:
  - /home/dwl/projects/factory/docker-dev/files:/home/dwl/files
  - /home/dwl/projects/factory/docker-dev/sites-available:/etc/apache2/sites-available
  - /home/dwl/projects/factory/docker-dev/ssl:/etc/apache2/ssl
  - /home/dwl/projects/factory/docker-dev/letsencrypt:/etc/letsencrypt
  stdin_open: true

d-apache-letsencrypt:
  ports:
  - 65505:22/tcp
  - 65506:80/tcp
  - 443:443/tcp
  environment:
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_SSH_ACCESS: 'true'
    DWL_USER_ID: '1000'
    DWL_SSLKEY_C: EU
    DWL_SSLKEY_ST: France
    DWL_SSLKEY_L: Vannes
    DWL_SSLKEY_O: davask web limited - docker container
    DWL_SSLKEY_CN: davaskweblimited.com
    DWL_CERTBOT_EMAIL: docker@davaskweblimited.com
  labels:
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: letsencrypt.davaskweblimited.com
  image: davask/d-apache-letsencrypt:2.4-u12.04
  volumes:
  - /home/dwl/projects/factory/docker-dev/files:/home/dwl/files
  - /home/dwl/projects/factory/docker-dev/sites-available:/etc/apache2/sites-available
  - /home/dwl/projects/factory/docker-dev/ssl:/etc/apache2/ssl
  - /home/dwl/projects/factory/docker-dev/letsencrypt:/etc/letsencrypt
  stdin_open: true

d-apache-openssl:
  ports:
  - 65505:22/tcp
  - 65506:80/tcp
  - 443:443/tcp
  environment:
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_SSH_ACCESS: 'true'
    DWL_USER_ID: '1000'
    DWL_SSLKEY_C: EU
    DWL_SSLKEY_ST: France
    DWL_SSLKEY_L: Vannes
    DWL_SSLKEY_O: davask web limited - docker container
    DWL_SSLKEY_CN: davaskweblimited.com
  labels:
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: openssl.davaskweblimited.com
  image: davask/d-apache-openssl:2.4-u12.04
  volumes:
  - /home/dwl/projects/factory/docker-dev/files:/home/dwl/files
  - /home/dwl/projects/factory/docker-dev/sites-available:/etc/apache2/sites-available
  - /home/dwl/projects/factory/docker-dev/ssl:/etc/apache2/ssl
  stdin_open: true

d-apache:
  ports:
  - 65503:22/tcp
  - 65504:80/tcp
  environment:
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_SSH_ACCESS: 'true'
    DWL_USER_ID: '1000'
  labels:
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: apache2.davaskweblimited.com
  image: davask/d-apache:2.4-u12.04
  volumes:
  - /home/dwl/projects/factory/docker-dev/files:/home/dwl/files
  - /home/dwl/projects/factory/docker-dev/sites-available:/etc/apache2/sites-available
  stdin_open: true

d-base:
  ports:
  - 65501:22/tcp
  environment:
    DWL_SSH_ACCESS: 'true'
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_USER_ID: '1000'
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: base.davaskweblimited.com
  image: davask/d-base:u12.04
  volumes:
  - /home/dwl/projects/factory/docker-dev:/home/dwl
  stdin_open: true

d-ubuntu:
  ports:
  - 65500:22/tcp
  environment:
    DWL_SSH_ACCESS: 'true'
    DWL_USER_NAME: dwl
    DWL_USER_PASSWD: dwl
    DWL_USER_ID: '1000'
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: ubuntu.davaskweblimited.com
  image: davask/d-ubuntu:14.04
  volumes:
  - /home/dwl/projects/factory/docker-dev:/home/dwl
  stdin_open: true
