d-apache-letsencrypt-proxy-reverse:
  ports:
  - 2222:22/tcp
  - 80:80/tcp
  - 443:443/tcp
  environment:
    DWL_USER_NAME: username
    DWL_USER_PASSWD: secret
    DWL_SSH_ACCESS: 'true'
    DWL_USER_ID: '1000'
    DWL_SSLKEY_C: EU
    DWL_SSLKEY_ST: France
    DWL_SSLKEY_L: Vannes
    DWL_SSLKEY_O: davask web limited - docker container
    DWL_SSLKEY_CN: davaskweblimited.com
    DWL_CERTBOT_EMAIL: docker@davaskweblimited.com
  labels:
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: proxy-reverse-letsencrypt.davaskweblimited.com
  image: davask/d-apache-letsencrypt-proxy-reverse:2.4-u14.04
  volumes:
  - /path/to/files:/home/username/files
  - /path/to/sites-available:/etc/apache2/sites-available
  - /path/to/ssl:/etc/apache2/ssl
  - /path/to/letsencrypt:/etc/letsencrypt
  stdin_open: true
